# Generated by Django 6.0.4 on 2026-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='upload_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='collection',
            name='upload_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='productimage',
            name='upload_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='C', max_length=1),
        ),
    ]
