# Generated by Django 6.0.4 on 2026-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_image_alter_collection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order within siblings'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active', 'position'], name='idx_category_parent_active_pos'),
        ),
    ]
