# Generated by Django 6.0.4 on 2026-04-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_category_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'address_type', 'id'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name', 'id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at', 'id'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'sku', 'id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date', 'id']},
        ),
    ]
