# Generated by Django 6.0.4 on 2026-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_fix_ordering_performance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'address_type'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'sku']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
    ]
